config/routes.rb
Rails.application.routes.draw do
  # resources :sessions, param: :username, only: [:index, :show, :new, :create, :destroy]
  # resources :users, only: [:new, :create, :show]
  # get '/games/:id/' , to: 'games#show'

  resources :questions, only: [:new, :create]
  resources :games, only: [:index, :new, :create, :show]
  # get '/games', to: 'games#lobby', as: 'lobby'

  resources :sessions, only: [:new, :create]
  resources :users, param: :username, only: [:new, :create, :show]
  get "/login", to: "sessions#new", as: :login
  delete "/byebye", to: "sessions#destroy", as: :logout
  post '/user_responses', to: 'games#user_responses', as: :user_responses
  get "/lose", to: 'games#lose'
  get "/create_new_game", to: 'games#create_new_game'
  post "/create_new_game", to: 'games#create_new_game'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :questions
    # has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :user_games
    has_many :game_questions
    has_many :users, through: :user_games
    has_many :questions, through: :game_questions
    belongs_to :user
    # belongs_to :category

    # def create_solo_game(params)
    #   @category = Category.find_by(id: params[:id].to_i)
    #   @questions = Question.all.select {|q| q.category_id == @category.id}
    #   @questions.sample(10)
    # end


end

app/models/game_question.rb
class GameQuestion < ApplicationRecord
    belongs_to :game
    belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :category
  has_many :game_questions
  has_many :games, through: :game_questions

  def answers
    @answer_choices = self.incorrect_answers.scan(/\b[a-zA-Z0-9]+[ ]?[a-zA-Z]*[ ]?[a-zA-Z]*[ ]?[a-zA-Z]*[ ]?[a-zA-Z]*[ ]?[a-zA-Z]*/)
    @answer_choices.push(self.correct_answer).shuffle
  end

end

app/models/session.rb
class Session < ApplicationRecord
    belongs_to :user	    


    def category_id
        @category = Category.find_by(id: params[:id])
    
    end	    
end	

app/models/user.rb
class User < ApplicationRecord
    has_many :user_games
    has_many :games, through: :user_games
    has_one :session
    has_secure_password
end

app/models/user_game.rb
class UserGame < ApplicationRecord
    belongs_to :user
    belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :is_authorized

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def logged_in?
    current_user != true
  end

  def is_authorized
    redirect_to new_user_path if !current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find_by(id: params[:id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def index
        @games = Game.all
        @category = Category.find_by(id: params[:id])
        @current_user = User.find_by(id: session[:user_id])
    end


    def show
      @game = Game.find_by(id: params[:id])
      @category = Category.find_by(id: @game.category_id)
      @current_user = User.find_by(id: session[:user_id])
      @questions = Question.all.select {|q| q.category_id == @category.id.to_i}
      @game_questions = @questions.sample(1)
      @current_user.question_asked = @game_questions[0].id.to_i
      @current_user.save
    end

    def user_responses
        @current_user = User.find_by(id: session[:user_id])
        @correct_answer = Question.find_by(id: @current_user.question_asked).correct_answer
        @game = Game.find_by(user_id: @current_user.id)
        if params[@correct_answer]
          @current_user.score ? @current_user.score += 1 : @current_user.score = 0
          @current_user.save
          redirect_to game_path(@game.id)
        else
          redirect_to lose_path
        end
    end

    def lose
      @current_user = User.find_by(id: session[:user_id])
      @current_user.score -= 10
      @current_user.save
    end

    def lobby
      @username = params[:username]
    end

    def new
      @questions = Question.all
      Game.new
    end

    def create
      if params["Create"] == "Start Game"
        @category = Category.find_by(id: params[:category][:category_id].to_i)
        @questions = Question.all.select {|q| q.category_id == @category.id}
        @game = Game.create(user_id: session[:user_id], category_id: @category.id)
        redirect_to game_path(@game.id)
      elsif params["Create"] == "Create Question"
        redirect_to new_question_path
      end
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @question = Question.new
  end

  def create
    # @category = Category.find_by(id: question_params[:category][:category_id].to_i)
    @question = Question.new(question_params)
    @question.category_id = 100
    if @question.save
      redirect_to games_path
    else
      @errors = @question.erorrs.full_messages
      render :new
    end
  end

  def question_params
    params.require(:question).permit(:prompt, :correct_answer, :category, :incorrect_answers => [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      @errors = ["Invalid username/password combination."]
      render :new
    end

  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized #before we do anything. check to see if this is the authorized user
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.score = 0
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @current_user = User.find_by(id: session[:user_id])
    @highscores = User.all[0..4].sort {|a, b| b.score <=> a.score }.map{ |user| [user.username, user.score] }
  end

  private

  def authorized
    if !current_user
      #if the user is not authrorized then redirect them to sign in
      redirect_to new_user_path
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<%= @category.name %>

app/views/games/index.html.erb
<img src="https://files.slack.com/files-pri/T02MD9XTF-FKTMEG33R/qq_logo_v2-01.png">

<% if @errors %>
<ul>
  <% @errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>



<h2>Your current score is <%= @current_user.score %></h2>
<!-- Solo Game -->
  <%# 1. collection_select %> <br>
    <%# 2. submit the category %> <br>

    <%= form_tag games_path do %>
     <label> Solo Game:</label><br>
       <%= collection_select :category, :category_id, Category.all, :id, :name %>
     <input type="submit" value="Start Game" name="Create"> <br>
   <% end %>

  <%#  3. redirect_to games/:id with the submitted category%>

<br>
 <%= form_tag games_path do %>
  <label>Create Game:</label><br>
    <%= collection_select :category, :category_id, Category.all, :id, :name %>
  <input type="submit" value="Create Question" name="Create"> <br>
<% end %>





<%# Create game %> <br> <br>
<%= button_to "Logout", "/byebye", method: :delete %>

app/views/games/lose.html.erb
<img src="https://files.slack.com/files-pri/T02MD9XTF-FKU0M4CF8/qq_logo_v2-02.png">
<h2>YOU LOSE</h2>
<%= link_to "Return to lobby", games_path %>
<h2> Your score has been lowered by 10 points. </h2>
<h3> May God have mercy on your soul. </h3>

app/views/games/new.html.erb
<!-- auto generate a game key, select 10 questions from 30 choices, then submit -->
<img src="https://files.slack.com/files-pri/T02MD9XTF-FKTMEG33R/qq_logo_v2-01.png">
<h2>Create a Game</h2>

<%= form_for @question do |f| %>
  <%= f.label :prompt %>
  <%= f.text_field :prompt %>
  <%= f.label :correct_answer %>
  <%= f.text_field :correct_answer %>
  <%= f.fields_for :incorrect_answers do |answer|%>
    <%= answer.label :answer_1 %>
    <%= answer.text_field :answer_1 %><br>
    <%= answer.label :answer_2 %>
    <%= answer.text_field :answer_2 %><br>
    <%= answer.label :answer_3 %>
    <%= answer.text_field :answer_3 %><br>
  <%end %>
  <%= f.submit "Submit Question" %>
<% end %>

app/views/games/show.html.erb
<img src="https://files.slack.com/files-pri/T02MD9XTF-FKTMEG33R/qq_logo_v2-01.png">
<h2>Category: <%= @category.name %></h2>
<h2><%= @current_user.username %></h2>
<h3>Score: <%= @current_user.score %>
<br>
<%# this form needs to go to a controller route for posting the game %>
<%= form_tag user_responses_path, method: "post" do %>
  <% @game_questions.each do |q| %>
    <p><%= q.prompt %></p>
    <% q.answers.each do |answer| %>
      <input type="radio" name="<%= answer %>" value="<%= answer %>"><%= answer %>
    <% end %>
  <% end %>
  <input type="submit" value="Submit" name="Submit"> <br>
<% end %>

<%= button_to "Quit Game", "/games", method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizQuest</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>

<body>

<div>

<%= yield %>
</div>
</body>
</html>

app/views/questions/new.html.erb
<h2>Create a new Question</h2>

<% if @errors %>
<ul>
  <% @errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @question do |f| %>
  <%= f.label :prompt %>
  <%= f.text_field :prompt %><br>
  <%= f.label :correct_answer %>
  <%= f.text_field :correct_answer %><br>
  <%= f.fields_for :incorrect_answers do |answer|%>
    <%= answer.label :incorrect_1 %>
    <%= answer.text_field :incorrect_1 %><br>
    <%= answer.label :incorrect_2 %>
    <%= answer.text_field :incorrect_2 %><br>
    <%= answer.label :incorrect_3 %>
    <%= answer.text_field :incorrect_3 %><br><br>
  <%end %>
  <%= f.submit "Submit Question" %>

  <%= link_to "Cancel", games_path %>
<% end %>

app/views/users/new.html.erb
<img src="https://files.slack.com/files-pri/T02MD9XTF-FKTMEG33R/qq_logo_v2-01.png">
<% if @errors %>
<ul>
  <% @errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<h3>Sign up for a QQ account</h3>

<%= form_for @user do |f| %>
  <%= f.label :username %> 
  <%= f.text_field :username %> <br>
  <%= f.label :password %>
  <%= f.password_field :password %> <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %> <br>
  <%= f.submit "Create an Account" %> <br> <br>
<% end %>

<%= link_to "Log in", login_path %>

app/views/users/show.html.erb
<img src="https://files.slack.com/files-pri/T02MD9XTF-FKTMEG33R/qq_logo_v2-01.png">
<h2>Hi there <%= @current_user.try(:username).capitalize %>!</h2>

<p>Your score is <%= @current_user.score %></p>

<% if logged_in? %>
  <%= button_to "Games", "/games", method: :get %>
  <%= button_to "Logout", "/byebye", method: :delete %>
<% else %>
  <%= button_to "Login", "/login", method: :get %>
<% end %>

<h2> Highscores </h2>
<% @highscores.each do |highscore| %>
<p><%= highscore.first %>
<%= highscore.last %>
</p>
<% end %>